//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 10:15:37 PM MSK 
//


package Candypackage;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for candyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="candyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caloric" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="candyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ingredients" type="{http://www.example.com/ingredients}ingredients"/>
 *         &lt;element name="nutritional" type="{http://www.example.com/candys}nutritional"/>
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.example.com/candys}idCandy" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "candyType", propOrder = {
    "name",
    "caloric",
    "candyType",
    "ingredients",
    "nutritional",
    "manufacturer"
})
public class CandyType {

    @XmlElement(required = true)
    protected String name;
    protected double caloric;
    @XmlElement(required = true)
    protected String candyType;
    @XmlElement(required = true)
    protected Ingredients ingredients;
    @XmlElement(required = true)
    protected Nutritional nutritional;
    @XmlElement(required = true)
    protected String manufacturer;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the caloric property.
     * 
     */
    public double getCaloric() {
        return caloric;
    }

    /**
     * Sets the value of the caloric property.
     * 
     */
    public void setCaloric(double value) {
        this.caloric = value;
    }

    /**
     * Gets the value of the candyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCandyType() {
        return candyType;
    }

    /**
     * Sets the value of the candyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCandyType(String value) {
        this.candyType = value;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * @return
     *     possible object is
     *     {@link Ingredients }
     *     
     */
    public Ingredients getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ingredients }
     *     
     */
    public void setIngredients(Ingredients value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the nutritional property.
     * 
     * @return
     *     possible object is
     *     {@link Nutritional }
     *     
     */
    public Nutritional getNutritional() {
        return nutritional;
    }

    /**
     * Sets the value of the nutritional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nutritional }
     *     
     */
    public void setNutritional(Nutritional value) {
        this.nutritional = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    @Override
    public String toString() {
        return "CandyType{" +
                "name='" + name + '\'' +
                ", caloric=" + caloric +
                ", candyType='" + candyType + '\'' +
                ", ingredients=" + ingredients +
                ", nutritional=" + nutritional +
                ", manufacturer='" + manufacturer + '\'' +
                ", id=" + id +
                '}';
    }
}
