//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 10:15:37 PM MSK 
//


package Candypackage;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="candy" type="{http://www.example.com/candys}candyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candy"
})
@XmlRootElement(name = "candys")
public class Candys {

    @XmlElement(required = true)
    protected List<CandyType> candy;

    /**
     * Gets the value of the candy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CandyType }
     * 
     * 
     */
    public List<CandyType> getCandy() {
        if (candy == null) {
            candy = new ArrayList<CandyType>();
        }
        return this.candy;
    }
    public void setCandy(List<CandyType> candy) {
        this.candy=candy;
    }

    @Override
    public String toString() {
        return "Candys{" +
                "candy=" + candy +
                '}';
    }
}
